INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (1,'1º Bachillerato de Ciencias');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (2,'2º Bachillerato de Ciencias');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (3,'1º Bachillerato de Humanidades y Ciencias Sociales');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (4,'2º Bachillerato de Humanidades y Ciencias Sociales');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (5,'1º Sistemas Microinformáticos y Redes');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (6,'2º Sistemas Microinformáticos y Redes');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (7,'1º Desarrollo de Aplicaciones Web');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (8,'2º Desarrollo de Aplicaciones Web');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (9,'1º Administración de Sistemas Informáticos en Red');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (10,'2º Administración de Sistemas Informáticos en Red');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (11,'1º Integración Social');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (12,'2º Integración Social');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (13,'1º Marketing y Publicidad');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (14,'2º Marketing y Publicidad');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (15,'1º Actividades Comerciales');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (16,'2º Actividades Comerciales');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (17,'1º Servicios Administrativos');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (18,'2º Servicios Administrativos');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (19,'1º Gestión Administrativa');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (20,'2º Gestión Administrativa');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (21,'1º Administración y finanzas A');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (22,'2º Administración y finanzas A');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (23,'1º Administración y finanzas B');
INSERT INTO `kalpataru_jorge`.`cursos` (id,`nombre`) VALUES (24,'2º Administración y finanzas B');